[project]
name = "hf-pytorch-ex"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "av>=18.1.0",
    "datasets>=5.0.1",
    "huggingface-hub>=1.30.0",
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
    "librosa>=1.0.0",
    "matplotlib>=3.11.1",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
    "requests>=2.34.2",
    "safetensors>=0.8.0",
    "scipy>=1.18.1",
    "seaborn>=0.13.2",
    "sentencepiece>=0.2.2",
    "soundfile>=0.14.0",
    "timm>=1.0.29",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "transformers>=5.16.1",
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu126" }
torchvision = { index = "pytorch-cu126" }
